name: Code Coverage

on:
  push:
    branches: [ "**" ]  # Trigger on all branches
  pull_request:
    branches: [ "main", "release/**" ]  # Trigger on PRs to main and release branches

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Full history needed
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x' # Adjust to your .NET version
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Run TUNIT tests with coverage
      run: |
        dotnet test --no-build --configuration Release \
          --collect:"XPlat Code Coverage" \
          --results-directory ./test-results \
          --logger "trx;LogFileName=TestResults.trx" \
          --logger "console;verbosity=detailed"
    
    - name: Generate Code Coverage Report
      uses: danielpalme/ReportGenerator-GitHub-Action@v5
      with:
        reports: ./test-results/**/coverage.cobertura.xml
        targetdir: ./coverage-report
        reporttypes: Html;Cobertura;MarkdownSummaryGithub

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          ./test-results/**/*.trx
          ./coverage-report/**/*
    
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: './test-results/**/*.trx'
        reporter: dotnet-trx
    
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ./coverage-report/Cobertura.xml
        badge: true
        fail_below_min: false # Set to true if you want to fail on low coverage
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '60 80' # Warning at 60%, error below 80%
    
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md