name: Publish on NuGet
 
on:
  push:
    branches: [ master ]
    paths: [ 'TvdbClient/**' ]
  workflow_dispatch:

env:
  NET_VERSION: '9.x'
  PROJECT_NAME: TvdbClient
  PROJECT_FILE: TvdbClient.csproj
  RELEASE_NAME: TvdbClient
  RELEASE_CONFIG: Release
  
jobs:
  publish:
    name: Publish on NuGet
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        
    - name: Setup .NET SDK ${{ env.NET_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.NET_VERSION }}
        dotnet-quality: 'ga'
        
    - name: Nerdbank.GitVersioning 
      uses: dotnet/nbgv@v0.4
      id: nbgv
      with:        
        path: ${{ env.PROJECT_NAME }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c ${{ env.RELEASE_CONFIG }} --no-restore

    - name: Package
      run: dotnet pack -c ${{ env.RELEASE_CONFIG }} -o . '${{ env.PROJECT_NAME }}/${{ env.PROJECT_FILE }}'
      
    - name: Publish on NuGet
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json  
      
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
          tag_name: v${{ steps.nbgv.outputs.NuGetPackageVersion }}
          release_name: ${{ env.RELEASE_NAME }} ${{ steps.nbgv.outputs.NuGetPackageVersion }}
          draft: false
          prerelease: false